### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by Ragansu**
Update documentation

This removed all old html since we have a github actions to build it on the fly in website repo

And make changes to rst files to make it look nice.
to see what this PR will do check this link. Its the local fork for the website with the new documentation changes
https://ragansu.github.io/FAIR-Universe.github.io/docs/

Please give your comments I will update accordingly 

RC

### CODE REVIEW

**Comment by cjh1** [comment]
@Ragansu I think there are two things we should add/change on landing page on codabench:

- Remove should remove the line about submitting untrained models
- We should mention that we will run submission once a day ( as in they will not run automatically )

**Comment by Ragansu** [comment]
Thanks @cjh1 . I will check and add this to the landing page.

**Comment by Ragansu** [comment]
> @Ragansu I think there are two things we should add/change on landing page on codabench:
> 
> * Remove should remove the line about submitting untrained models
> * We should mention that we will run submission once a day ( as in they will not run automatically )

I was discussing this with ihsaan,
@cjh1 when you landing page you mean the Overview Page in coda-bench or the website ?

**Comment by ihsaan-ullah** [comment]
If you remove the docs folder, we should pull back the pages folder and put it in this repository

**Comment by Ragansu** [comment]
So the idea was to move things participants dont need out of this repository. which includes pages. 
The pages will be copied to FairUniverse.github.io page

**Comment by ihsaan-ullah** [comment]
Pages are part of the competition bundle. They should be in this repository.

**Comment by ihsaan-ullah** [comment]
For participants, we should improve the `README.md`.

**Comment by Ragansu** [comment]
I dont disagree, But I am following up on what @SaschaDief and @jvdudley mentioned about simplifying, the HEP reporsitory

see https://github.com/FAIR-Universe/Organization/issues/20

**Pull request merged**
