### PR TITLE
Parallelize testing

### PR DESCRIPTION
**Pull request by cjh1**
The parallelization is performed using a process pool and shared memory to hold the test data.

### CODE REVIEW

**Comment by cjh1** [comment]
@Ragansu This is working for the test model I have been using. If you can point me at some more models to test with that would be great.

**Comment by Ragansu** [comment]
@cjh1 You mean something other than NN_method right, which gives reasonable results.  I will try to get it by Monday.  I will ping you when I am done.

**Comment by cjh1** [comment]
@Ragansu Yes, we need to test on a variety of model to confirm the multiprocessing works with other package, such as PyTorch.

**Comment by Ragansu** [comment]
I will first work with DANN and later see if I can make a pytorch version of DANN.

**Comment by cjh1** [comment]
This is working for pytorch and tensorflow

**Comment by Ragansu** [comment]
Can you test XGB ? just to be sure ?

**Comment by cjh1** [comment]
> Can you test XGB ? just to be sure ?

Sure, which model is that?

**Comment by cjh1** [comment]
`XGB_1` ?

**Comment by Ragansu** [comment]
It should be XGB_NLL but I have changed few things for pytorch so just to be sure. I will clean it up a bit and test it in serial ingestion. I will ping you when I am done. Optimistically in an hour.

**Comment by Ragansu** [comment]
XGB_NLL is ready for testing. sorry for the wait.

**Comment by cjh1** [comment]
> XGB_NLL is ready for testing. sorry for the wait.

NP, I can confirm it works with XGB_NLL

**Review by Ragansu — COMMENTED** [review]
Looks pretty good, I will let @ihsaan-ullah do the merging.

**Review by ihsaan-ullah — APPROVED** [review]
looks good

**Pull request merged**
