### PR TITLE
Fixed bugs in Statistics Analysis and Renaming dataset for clearer understanding 

### PR DESCRIPTION
**Pull request by AvencastF**
Open the MR first to tell people this work. 

Fix some bugs/problems when testing the latest systematics results.

### CODE REVIEW

**Comment by Ragansu** [comment]
I already corrected the predict function issue in another PR. It was a mistake from my side 

Please check with a the latest commit. 
sorry for the trouble 

RC

**Comment by AvencastF** [comment]
@Ragansu Could you help resolve the confict here?

**Comment by Ragansu** [comment]
The change in dataset was removed since its supposed to work out of the both out without any input parameters as it downloads the data set to the current working directory . to simplify things. If you disagree please discuss with @ihsaan-ullah  and @cjh1. 

For the rest I fixed the same issue you fixed hence the conflict was from white spaces 

Thanks 
RC

**Comment by AvencastF** [comment]
> For the rest I fixed the same issue you fixed hence the conflict was from white spaces

Thanks for fixing the conflicts. 

> The change in dataset was removed since its supposed to work out of the both out without any input parameters as it downloads the data set to the current working directory . to simplify things. If you disagree please discuss with @ihsaan-ullah and @cjh1.

The change here for the dataset doesn't affect the original usage way. In the current application, the program will re-download the public dataset if the zip file does not exist (from this line [[link](https://github.com/FAIR-Universe/HEP-Challenge/blob/master/ingestion_program/datasets.py#L209)]), which is unnecessary.

**Comment by Ragansu** [comment]
The idea is to avoid redownloading the data-sets. but zip file as check for that may not be ideal. we could keep other check like unziped files themselves.

**Comment by jvdudley** [comment]
@Ragansu did you fix the same issues that @AvencastF fixed in statistical_analysis.py, and if so, can those fixes be merged into the master branch? It looks like those bugs are still present.

**Comment by Ragansu** [comment]
I fixed some of the bugs that Yulei had address. But I already edited his PR on that so any more changes had to come from Yulei itself I haven't done anything. @AvencastF Let me know when your PR is ready for review

**Comment by AvencastF** [comment]
@Ragansu Please check the renaming. I've removed the dataset modification.

**Review by Ragansu — COMMENTED** [review]
looks good

**Review by Ragansu — APPROVED** [review]
It seems good I will merge this and use this as test for the rest

Thank You @AvencastF 

RC

**Pull request merged**
