### PR TITLE
Fix overview

### PR DESCRIPTION
**Pull request by Ragansu**
I have updated the Overview Page and added an extra page to act as a Front page please give you comment

RC

### CODE REVIEW

**Comment by wbhimji** [comment]
Thanks! I think this reorg makes sense. Some comments: 
- Don't think you need the dates (Sep to Oct 2024) because its there in codabench and we might extend and also intend for it to be available long term 
- "HEP and Machine Learning" -. "High-energy Physics (HEP) Machine Learning" (since its the first time a non-hep person will encounter I think) 
- Similarly to not scare the non-HEP people "The context is the measurement of the $H \rightarrow \tau^+ \tau^-$ cross section like in [HiggsML challenge on Kaggle](https://www.kaggle.com/c/higgs-boson) in 2014, from a dataset of the 4-momentum signal state" -> "The context is measurements of the Higgs boson building on the previous  [HiggsML challenge on Kaggle](https://www.kaggle.com/c/higgs-boson) from 2014" (and drop 4-momentum etc.)
- Could also drop "from which correct coverage will be evaluated automatically from pseudo-experiments " IMO 
- Can move down "## How to join this challenge?" to below the links
- [Tutorial Slides]is repeated in the [Codabench] so I suggest remove "Also, see the [tutorial slides]" from the later and move "[Tutorial Slides]"  bullet below the [Codabench]" one
- I think we can merge "Submissions" with "How to join" and as should just "This competition allows code submissions. Participants are strongly encouraged to submit code with a pre-trained model, rather than retraining within the execution to allow evaluation within the resources available"

**Comment by Ragansu** [comment]
I will make these changes and ping you. Hopefully we can get it merged today.

**Comment by dhrou** [comment]
where will front page be, is this a new page to go in Cdabench ? 

In any case for front page : 

First line : This is a [NeurIPS 2024 competition](https://neurips.cc/Conferences/2024/CompetitionTrack)

This High-energy Physics (HEP) Machine Learning competition is the first to s
==>
This  Machine Learning competition is one of the first to ... (and then mention HEP in the next sentence). (to avoid people feeling excluded already at the first line)

**Comment by SaschaDief** [comment]
With the changes proposed by Wahid, I think this seems reasonable

**Pull request merged**
